# Generated by Django 3.2 on 2021-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_glasses_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='bet',
            field=models.TextField(default='', max_length=50, verbose_name='پیش نویس'),
        ),
    ]
