# Generated by Django 3.2.6 on 2021-08-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_glasses_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='image2',
            field=models.ImageField(blank=True, default='def.jpg', upload_to='img/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='image3',
            field=models.ImageField(blank=True, default='def.jpg', upload_to='img/', verbose_name=''),
        ),
    ]
