# Generated by Django 3.0.4 on 2021-08-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210811_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fav',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homeview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='us',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('hmd', 'همدان'), ('mal', 'ملایر'), ('nah', 'نهاوند'), ('tos', 'تویسرکان'), ('kab', 'کبودرآهنگ'), ('asd', 'اسدآباد'), ('bah', 'بهار'), ('rzn', 'رزن'), ('dar', 'درگزین')], default='hmd', max_length=3)),
                ('address', models.CharField(default='', max_length=100)),
                ('pelak', models.CharField(default='', max_length=15)),
                ('floor', models.CharField(default='', max_length=15)),
                ('post', models.CharField(default='', max_length=15)),
                ('name', models.CharField(default='', max_length=15)),
                ('lastname', models.CharField(default='', max_length=15)),
                ('number', models.CharField(default='', max_length=15)),
                ('house_number', models.CharField(default='', max_length=15)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.glasses')),
            ],
        ),
    ]
