# Generated by Django 3.0.4 on 2021-08-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210829_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='post',
            new_name='postcode',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='pelak',
        ),
    ]
