# Generated by Django 3.0.4 on 2021-09-18 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_checkout_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='house_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator('^[#](\\w+)$', "Hashtag doesn't comply.")]),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='bet',
            field=models.TextField(default='', max_length=100, verbose_name='پیش نویس'),
        ),
    ]
