# Generated by Django 3.0.4 on 2021-09-18 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210918_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator('[0-9]{11}', 'شماره ی تلفن صحیح نیست')]),
        ),
    ]
