# Generated by Django 3.0.4 on 2021-09-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210918_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='us',
            name='image1',
            field=models.ImageField(blank=True, default='def.jpg', upload_to='img/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='us',
            name='image2',
            field=models.ImageField(blank=True, default='def.jpg', upload_to='img/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='us',
            name='image3',
            field=models.ImageField(blank=True, default='def.jpg', upload_to='img/', verbose_name=''),
        ),
    ]
