# Generated by Django 3.0.4 on 2021-09-20 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210918_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='house_number',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator('[0-9]', 'تلفن ثابت صحیح نیست ')]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator('[0-9]{10,11}', 'تلفن همراه صحیح نیست ')]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='postcode',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{10}', ' کدپستی صحیح نیست ')]),
        ),
    ]
