# Generated by Django 3.0.4 on 2021-09-20 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210920_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='tracing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='house_number',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator('[0-9]{8,11}', 'تلفن ثابت صحیح نیست ')]),
        ),
    ]
